"""database update projects link

Revision ID: 4c39204e678a
Revises: ddff6b1132a2
Create Date: 2023-11-27 17:16:29.578320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c39204e678a'
down_revision = 'ddff6b1132a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_repo', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('link_repo')

    # ### end Alembic commands ###
