"""Update database 1

Revision ID: ddff6b1132a2
Revises: 8aa143d8834f
Create Date: 2023-11-23 17:33:35.191690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddff6b1132a2'
down_revision = '8aa143d8834f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint('_project_user_uc', ['project_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('_project_user_uc', type_='unique')

    # ### end Alembic commands ###
